wallpaper {
    monitor = HDMI-A-2
    path = /home/sebastian/dotfiles/wallpapers/mac-os.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/sebastian/dotfiles/wallpapers/mac-os.jpg
    fit_mode = cover
}

splash = false
ipc = off
